### ISSUE TITLE
problem installing the plugin on mautic

### ISSUE THREAD

**Issue by johanflorez** [kuzmany/mautic-custom-tags-bundle#4]
hi, im installing the plugin with composer like instructions, but after installing, mautic show:
Fatal error: Uncaught Error: Class 'Mautic\CoreBundle\ErrorHandler\ErrorHandler' not found in /var/www/html/index.php:29 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 29
help please

**Comment by kuzmany** [comment]
What version of Mautic?
Did you install by composer?
Or manual copy and clear cache app/cache/prod/
Check your composer.json from root, it's empty?

**Comment by kuzmany** [comment]
If composer.json contain just plugin info, thet download composer.json from Mautic github, run `composer install`  and then install plugin again.

I don't know why, but composer sometime  make this things mad.

**Comment by johanflorez** [comment]
Hi
I finally could make it work
I restore some things from one backup I had made previously
And yes i found that was important to clear cache
So, thanks for your time
Bye

**Comment by johanflorez** [comment]
Hi again!
thanks so much for the plugin, it works very well
bye
